spring:
  application:
    name: greeting-service
  cloud:
    config:
      import-check:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'

greeting-service:
  greeting: "Cia"
  default-value: "Mundo prod"